//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixel.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attempts
    {
        public int IdAttempts { get; set; }
        public int IdUser { get; set; }
        public int IdTest { get; set; }
        public int Scores { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
